### ISSUE TITLE
a

### ISSUE THREAD

**Issue by bianjunfeng** [Dongdii/lsh_sk#1]
在gayhub还整收费  是不是脑残？

**Comment by Dongdii** [comment]
好兄弟，我找到了就是收费版本啊。。只是方便本校学生刷点课。我也想有免费的。词达人和welearn和学xx国不是免费的吗？

码就对了 ***@***.***> 于 2022年3月11日周五 15:00写道：

**Comment by wish2831** [comment]
nb   试一下好不好用

**Comment by MirrAKe** [comment]
谢谢hxd！想问一下词达人里面的QQ群已经没了，有新的群嘛？学习通和智道在油猴上有刷课的脚本，只是不能考试

**Comment by Dongdii** [comment]
> 谢谢hxd！想问一下词达人里面的QQ群已经没了，有新的群嘛？学习通和智道在油猴上有刷课的脚本，只是不能考试

群在啊，1085739587，群名 请好好学习。没必要用脚本平台也就一块钱，还稳。

**Comment by Dongdii** [comment]
> 谢谢hxd！想问一下词达人里面的QQ群已经没了，有新的群嘛？学习通和智道在油猴上有刷课的脚本，只是不能考试

可以用邮箱联系我hat_coder02@icloud.com

**Comment by MirrAKe** [comment]
![image](https://user-images.githubusercontent.com/76761109/159216514-ab8b0ceb-2026-44a0-b9a3-3ce6d5f8de74.png)
可能是群设置了不能被搜索到？

**Comment by Dongdii** [comment]
> ![image](https://user-images.githubusercontent.com/76761109/159216514-ab8b0ceb-2026-44a0-b9a3-3ce6d5f8de74.png)
> 可能是群设置了不能被搜索到？

hxd直接加我，2924646939
