### ISSUE TITLE
题型11答案查询出错

### ISSUE THREAD

**Issue by ab-Royo** [Dongdii/lsh_sk#4]
[Info] 15/87.[mode:11]They  are  creating  a  major  shift  in  the  social  experiences  of  both  children  and  {adolescents}.(他们使儿童和青少年的社会经历产生了重大的转变。)
find_answer_by_11
They  are  creating  a  major  shift  in  the  social  experiences  of  both  children  and  {adolescents}.
adolescents
[{'content': 'noun 挖苦；嘲笑；讽刺', 'remark': None, 'answer': None, 'answer_tag': 0, 'check_code': None, 'sub_options': None, 'ph_info': None}, {'content': 'noun 青少年', 'remark': None, 'answer': None, 'answer_tag': 1, 'check_code': None, 'sub_options': None, 'ph_info': None}, {'content': 'noun 祸根；恐吓；威胁', 'remark': None, 'answer': None, 'answer_tag': 2, 'check_code': None, 'sub_options': None, 'ph_info': None}, {'content': 'adj 青少年的；青春期的', 'remark': None, 'answer': None, 'answer_tag': 3, 'check_code': None, 'sub_options': None, 'ph_info': None}]
[]

[Warning] 题型11答案查询出错！

**Comment by Dongdii** [comment]
思政版教材不支持

actRoyo ***@***.***> 于 2022年7月18日周一 13:17写道：
